Add a user guide with examples
rust-lang/cargo-bisect-rustc pull request #266
Opened 2023-03-20 02:37 UTC by ehuss

This replaces the old tutorial with a new book that goes into more detail on various topics. It also contains a suite of examples to show different uses.

Closes #264

2023-03-20 02:37 UTC, ehuss commented
There is a preview of what this looks like at: https://ehuss.github.io/cargo-bisect-rustc/introduction.html

2023-03-20 13:48 UTC, LingMan commented on .github/workflows/docs.yml
Github has published starter workflows for publishing with Github Actions. I'd probably base this one on the mdBook workflow they've published instead of inventing my own.

Docs: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
mDbook starter workflow: https://github.com/actions/starter-workflows/blob/main/pages/mdbook.yml

I also suspect that pinning the mdBook version will quickly result in outdated versions being used to build. Pretty sure Dependabot won't open PRs to update it.
One option would be `cargo install mdbook` but running that on each push is a waste of cpu cycles. Instead you could install it with `taiki-e/install-action`. That action gets regular updates so far, so I'd trust it more to stay up-to-date until proven otherwise.

Usage would be:
```
- uses: taiki-e/install-action@v2
  with:
    tool: mdbook
```

2023-03-31 15:12 UTC, ehuss commented
@oli-obk Just checking if you had any thoughts on this?

2023-03-31 15:48 UTC, oli-obk requested changes
Looks good to me. I didn't check that everything was moved, but the summary looks good

2023-03-31 15:48 UTC, oli-obk commented on .github/workflows/docs.yml
> +        curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.28/mdbook-v0.4.28-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
maybe put the version into an env var so it is easy to update?

2023-03-31 20:16 UTC, oli-obk approved these changes

2023-03-31 20:16 UTC, merged